### ISSUE TITLE
Invoking `swift-test.exe` fails using the 5.6.1 toolchain

### ISSUE THREAD

**Issue by tofugarden** [MaxDesiatov/swift-windows-action#3]
### Overview

I am consistently getting the following error when using the 5.6.1 toolchain:
```
error: unable to invoke subcommand: C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift-test.exe ()
```

### Output

* [A successful run on 5.6](https://github.com/crichez/swift-logbook/runs/6491668953?check_suite_focus=true)
* [A failed run on 5.6.1](https://github.com/crichez/swift-logbook/runs/6491744024?check_suite_focus=true)

### Additional Context

The runs above use async tests, so the jobs ultimately fail. The first does actually get to run the `swift test` command though, so that's what I mean by "successful" 🙃. I'm just learning about the lack of async test support on Windows but wanted to test it on the latest toolchain before I dig deeper (although it sounds like nothing has changed).

**Comment by crichez** [comment]
Same thing happens on a Windows host, I'll be sure to check that before creating issues. Thanks!

**Comment by MaxDesiatov** [comment]
Thanks for checking! I also recommend searching for an issue or creating a new one on `apple/swift` repo to make sure that toolchain folks are aware of it.

**Comment by kelvin13** [comment]
this is also happening with 5.6.2 :(

**Comment by MaxDesiatov** [comment]
Please create an issue in `apple/swift` repo for tracking this. I'm convinced that the action itself is not causing this.
